### ISSUE TITLE
Crosswalk cordova integration error

### ISSUE THREAD

**Issue by farafonov-alexey** [ks32/CrosswalkNative#1]
I successfully build your xwalk_core_library_58.aar with cordova, however when the app starting the roor occured
```
 Caused by: java.lang.NoSuchMethodException: getAssignedPackageIdentifiers []
     at java.lang.Class.getConstructorOrMethod(Class.java:472)
     at java.lang.Class.getMethod(Class.java:857)
     at org.xwalk.core.internal.XWalkViewDelegate.<clinit>(XWalkViewDelegate.java:69)
     at java.lang.reflect.Method.invokeNative(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:515) 
     at org.xwalk.core.ReflectMethod.invoke(ReflectMethod.java:61) 
     at org.xwalk.core.XWalkCoreWrapper.checkCoreArchitecture(XWalkCoreWrapper.java:349) 
     at org.xwalk.core.XWalkCoreWrapper.findEmbeddedCore(XWalkCoreWrapper.java:248) 
     at org.xwalk.core.XWalkCoreWrapper.attachXWalkCore(XWalkCoreWrapper.java:162) 
     at org.xwalk.core.XWalkLibraryLoader$ActivateTask.doInBackground(XWalkLibraryLoader.java:335) 
     at org.xwalk.core.XWalkLibraryLoader$ActivateTask.doInBackground(XWalkLibraryLoader.java:317) 
     at android.os.AsyncTask$2.call(AsyncTask.java:288) 
     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
```

I' tried to search method getAssignedPackageIdentifiers at tenta-browser's  XWalkViewDelegate.java - https://github.com/tenta-browser/crosswalk/blob/master/runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
But this entire method doesn't exsists. 
Do you have any workaround?  Maybe I need to recompile xwalk_core_library.jar somehow.

**Comment by farafonov-alexey** [comment]
I see it was intetionally added here - https://github.com/ks32/crosswalk/commit/2fc4bc5cff9f9386793b9a26d5879308a2744f9b#diff-32a8c099ccb75ea20046fd6c07ff5a8fR69

**Comment by ks32** [comment]
You can rebuild crosswalk. Use docker image https://hub.docker.com/r/ks32/crosswalk-build-tools
It has all tools and just ready for building.

**Comment by farafonov-alexey** [comment]
So i've succefully started the container and followed by [instruction](https://crosswalk-project.org/contribute/building_crosswalk/android_build.html) fetched the source with gclient sync.
* in **crosswalk/src** directory the command '**gn args out/Default**' was executed with non-default params:
```
import("//xwalk/build/android.gni")
target_os = "android"
proprietary_codecs=true
ffmpeg_branding = "Chrome"
```
without last two lines i have assertion fault ffmpeg_branding!=Chromium
* trying to build crosswalk with command '**ninja -C out/Default xwalk_core_library**' in the same directory.
But the error occured:
```
FAILED: libxwalkcore.cr.so libxwalkcore.cr.so.TOC lib.unstripped/libxwalkcore.cr.so
python "/root/crosswalk/src/build/toolchain/gcc_solink_wrapper.py" --readelf="../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-readelf" --nm="../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm" --strip=../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip --sofile="./lib.unstripped/libxwalkcore.cr.so" --tocfile="./libxwalkcore.cr.so.TOC" --output="./libxwalkcore.cr.so"  -- ../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -shared -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--as-needed -fuse-ld=gold -Wl,--icf=all -Wl,--build-id=sha1 -Wl,--no-undefined -Wl,--exclude-libs=libgcc.a -Wl,--exclude-libs=libc++_static.a -Wl,--exclude-libs=libvpx_assembly_arm.a -Werror -nostdlib -Wl,--warn-shared-textrel --sysroot=../../third_party/android_tools/ndk/platforms/android-16/arch-arm  -Wl,--version-script=/root/crosswalk/src/build/android/android_only_explicit_jni_exports.lst -Wl,-wrap,calloc -Wl,-wrap,free -Wl,-wrap,malloc -Wl,-wrap,memalign -Wl,-wrap,posix_memalign -Wl,-wrap,pvalloc -Wl,-wrap,realloc -Wl,-wrap,valloc -L../../third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -o "./lib.unstripped/libxwalkcore.cr.so" -Wl,-soname="libxwalkcore.cr.so" @"./libxwalkcore.cr.so.rsp"
../../third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/memory:2431: error: undefined reference to 'content::DevToolsHttpHandler::~DevToolsHttpHandler()'
../../third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/memory:2431: error: undefined reference to 'content::DevToolsHttpHandler::~DevToolsHttpHandler()'
../../xwalk/runtime/browser/android/xwalk_dev_tools_server.cc:173: error: undefined reference to 'content::DevToolsHttpHandler::DevToolsHttpHandler(content::DevToolsManagerDelegate*, std::__ndk1::unique_ptr<content::DevToolsSocketFactory, std::__ndk1::default_delete<content::DevToolsSocketFactory> >, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, base::FilePath const&, base::FilePath const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
../../third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/memory:2431: error: undefined reference to 'content::DevToolsHttpHandler::~DevToolsHttpHandler()'
../../third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/memory:2431: error: undefined reference to 'content::DevToolsHttpHandler::~DevToolsHttpHandler()'
../../xwalk/runtime/browser/devtools/remote_debugging_server.cc:169: error: undefined reference to 'content::DevToolsHttpHandler::DevToolsHttpHandler(content::DevToolsManagerDelegate*, std::__ndk1::unique_ptr<content::DevToolsSocketFactory, std::__ndk1::default_delete<content::DevToolsSocketFactory> >, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, base::FilePath const&, base::FilePath const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
Is there any workaround for this?

**Comment by ks32** [comment]
I am using following args:
gn args out/Default_arm
`import("//xwalk/build/android.gni")
is_debug = false
target_os = "android"
enable_nacl = false
symbol_level = 0
remove_webcore_debug_symbols = true
target_cpu = "arm"
use_aura=false
use_ozone=false
enable_plugins=false
disable_bundled_extensions=true
ffmpeg_branding = "Chrome" #disable to reduce size
proprietary_codecs=true #disable to reduce size
v8_use_snapshot=true
enable_webrtc=false #disable to reduce size
pdf_enable_v8=false
multidex_in_release=true
is_official_build=true
v8_enable_i18n_support=false
disable_ftp_support=true
disable_libfuzzer=true
enable_basic_print_dialog=false`

ninja -C out/Default_arm xwalk_core_library
It should work. You can change arguments if you want.

**Comment by farafonov-alexey** [comment]
Thank you.
I've successfully build xwalk_core_library with your parameters.
Is there any param to enable Web Sql support in xwalk?

**Comment by ks32** [comment]
check arguments for what you are looking for:
gn args out/Default_arm --list

**Comment by farafonov-alexey** [comment]
Well it seems that websql is turned on by default, but using it lead to error:
```
there was not enough remaining storage space, or the storage quota was reached and the user declined to allow more space
```
![image](https://user-images.githubusercontent.com/33369984/46292768-62eaf180-c59a-11e8-8b33-b52d4d9fac24.png)

Maybe xwalk source code needs changing?

**Comment by farafonov-alexey** [comment]
Well I've successfully integrated this xwalk_core_library to our Cordova project at last.
We switched from WebSql to https://github.com/litehelpers/Cordova-sqlite-storage.git plugin.

One more thing. I see in tenta-browser/crosswalk repository there are branches - chromium_59 and chromium_64. According to your [comment ](https://github.com/crosswalk-project/crosswalk/issues/4001#issuecomment-419827722 ) this chromium versions could be used too.

Is there any chance that you can remove your private libraries from these branches too?
Or is there some kind of instruction with help of which I can do it myself?

**Comment by ks32** [comment]
First, I am not link to tenta nor do know what they do. Regarding chromium_64, I can work on it after 2-3 months because of my current work. 

It is not difficult to remove private libraries. If you look at ks_chromium_58, there are not many changes with chromium_58. You just need to apply similar changes to chromium_64 to make it work.

**Comment by martinlombana** [comment]
Did anyone make it work with chromium_64?

Does anyone has an .aar to share or instructions? Thanks :)
