### ISSUE TITLE
H264 Baseline Main  High profiles

### ISSUE THREAD

**Issue by HYRobin** [ks32/CrosswalkNative#11]
Hi Mr ks32 , i pull the old deep_tool and can buid successfully, another problem is that h264 seems to be Baseline, how i can choose Main and High profiles in H264.  thank you very much!

**Comment by ks32** [comment]
you will need to ask this to chromium/webrtc forum.
https://bugs.chromium.org/p/webrtc/issues/detail?id=8584
also remember it is chromium 58.
