### ISSUE TITLE
Ndk and Sdk can not be downloaded automatically

### ISSUE THREAD

**Issue by shenjiesky** [ks32/CrosswalkNative#12]
Many packages of dependency in third_party is not downloaded  automatically, such as Ndk and Sdk. When I run "./install-build-deps.sh./install-build-deps-android.sh",it got no mistakes,but ndk and sdk was not download.I am confused by the problem. I would appreciate it if you could offer me any help.

**Comment by ks32** [comment]
are you using crosswalk-build-tools docker image? also did you run: gclient sync

**Comment by shenjiesky** [comment]
yes i have ran “gclient sync”

and my environment is ubuntu 16.04

**Comment by ks32** [comment]
install-build-deps-android.sh should install sdk/ndk. You should check for
errors.
