### ISSUE TITLE
how i can upgrade crosswalk to chromium 77 or 80

### ISSUE THREAD

**Issue by HYRobin** [ks32/CrosswalkNative#15]
hi Mr32   i finally find  why app don't work  on android 10.  because android 10 has forbidden app create share menory with /dev/file,  it will throw erros like  'avc denied {open} xxx',  i want to know if i can upgrade to chromium 77 or 80 in your project  https://github.com/ks32/crosswalk/tree/ks_chromium_58.  how can i do it, please help me thanks very much!!

**Comment by ks32** [comment]
https://github.com/crosswalk-project/crosswalk-website/wiki/Rebasing-our-forks
