### ISSUE TITLE
Android 10, crash when trying to loadUrl

### ISSUE THREAD

**Issue by hellcan** [ks32/CrosswalkNative#17]
Hello Sir,

I currently using the Crosswalk with the embedded mode in my App. And In Android 10, The Crosswalk webView will crash and give me these errors when the crosswalk webview load any url. For the version below Android 10, the webView works perfectly fine. Looks like these Android Q changes had a big impact on the Crosswalk Webview. Could you give me some advice to solve it?

@ks32 may I know your email address, I can provide some fund contribution for this fix

Thanks 
```
[ERROR:compositor_impl_android.cc(585)] Failed to init OutputSurface for compositor.
[ERROR:compositor_impl_android.cc(585)] Failed to init OutputSurface for compositor.
[FATAL:compositor_impl_android.cc(586)] Too many context creation failures. Giving up... 
------- beginning of crash
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 13597 (treader.r2.main), pid 13597 (treader.r2.main)
```

**Comment by ks32** [comment]
Check the last update.

**Comment by hellcan** [comment]
Thank you, I will try again

**Comment by cedarln** [comment]
Hi, have you solved this ?
