### ISSUE TITLE
Android 10, crash

### ISSUE THREAD

**Issue by hellcan** [ks32/CrosswalkNative#18]
Hello Sir,

I just tried the latest updates, and when I try to upgrade the version to 29 (Android 10). When the webView trying to initialize and load URL. It will still crash and gives me these error messages.
![image](https://user-images.githubusercontent.com/7111856/79296097-70c84500-7ea8-11ea-9efd-00f12cae6e0c.png)

Could you give me some advice to solve it?

@ks32 may I know your email address, I can provide some fund contribution for this fix

Thank you
 ```
E/chromium: [ERROR:compositor_impl_android.cc(685)] Failed to init ContextProvider for compositor.
E/chromium: [ERROR:compositor_impl_android.cc(685)] Failed to init ContextProvider for compositor.
A/chromium: [FATAL:compositor_impl_android.cc(686)] Too many context creation failures. Giving up... 
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 24514 (rosswalk_native), pid 24514 (rosswalk_native)
```

**Comment by ks32** [comment]
Is it emulator? No problem on my side in Android 10.


Quran Majeed for iOS and Android
<https://quranmajeed.page.link/RGhFYwtYUVwBbTnB9>

Pakistan Data Management Services
p: +92 21 3455 9003
w: www.pakdata.com
<https://facebook.com/pakdata>   <https://twitter.com/hashtag/Pakdata>
<https://www.instagram.com/pakdataapps/>

**Comment by hellcan** [comment]
it's in my Samsung S9, and in your last update, you changed the compile version/ target version to 28, which is Android 9. But Android 10 will be version 29

**Comment by ks32** [comment]
Currently Chrome 58 will not compile with sdk 29. Compile SDK 28 should
have no issues with Android 10. I am using it successfully in my app with
more than 5 million users.



Quran Majeed for iOS and Android
<https://quranmajeed.page.link/RGhFYwtYUVwBbTnB9>

Pakistan Data Management Services
p: +92 21 3455 9003
w: www.pakdata.com
<https://facebook.com/pakdata>   <https://twitter.com/hashtag/Pakdata>
<https://www.instagram.com/pakdataapps/>

**Comment by hellcan** [comment]
but I have to upgrade my App to SDK 28, may I fund you for the SDK29 compatibility fix? Thanks

**Comment by ks32** [comment]
sure.

Quran Majeed for iOS and Android
<https://quranmajeed.page.link/RGhFYwtYUVwBbTnB9>

Pakistan Data Management Services
p: +92 21 3455 9003
w: www.pakdata.com
<https://facebook.com/pakdata>   <https://twitter.com/hashtag/Pakdata>
<https://www.instagram.com/pakdataapps/>

**Comment by hellcan** [comment]
may I know your email address, and we can discuess in detail

**Comment by ks32** [comment]
asif@pakdata.com

Quran Majeed for iOS and Android
<https://quranmajeed.page.link/RGhFYwtYUVwBbTnB9>

Pakistan Data Management Services
p: +92 21 3455 9003
w: www.pakdata.com
<https://facebook.com/pakdata>   <https://twitter.com/hashtag/Pakdata>
<https://www.instagram.com/pakdataapps/>

**Comment by JUSTINGBB** [comment]
"Gladle" is set to "compileSdkVersion 29" "targetSdkVersion 28" can solve my problem, I just use crosswalk to load local html

**Comment by ks32** [comment]
yes compileSdkVersion 29 is not yet supported

Quran Majeed for iOS and Android
<https://quranmajeed.page.link/RGhFYwtYUVwBbTnB9>

Pakistan Data Management Services
p: +92 21 3455 9003
w: www.pakdata.com
<https://facebook.com/pakdata>   <https://twitter.com/hashtag/Pakdata>
<https://www.instagram.com/pakdataapps/>
