### ISSUE TITLE
Android 5.1 crash (xwalk_core_library58)

### ISSUE THREAD

**Issue by SithisDev** [ks32/CrosswalkNative#20]
Hey. Tested your creation. It works fine on emulators. On a real device, android 5.1 application crashes when using WebAssembly and other tasks. The two most common mistakes are:

1)
W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[31,tid=27028,Native,Thread*=0x93dc1800,peer=0x12c06280,"Thread-6669"]
A/art: art/runtime/thread.cc:1067] Native thread exited without calling DetachCurrentThread: Thread[31,tid=27028,Native,Thread*=0x93dc1800,peer=0x12c06280,"Thread-6669"]
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 27028 (Thread-6669)

2)
I/XWalkWebResponseInternal.waitUntilReady(): Called [6690][Thread-6690]
I/XWalkWebResponseInternal.waitUntilReady(): Called [6658][Chrome_IOThread]
    Called [6658][Chrome_IOThread]
    Called [6658][Chrome_IOThread]
    Called [6658][Chrome_IOThread]
    Called [6658][Chrome_IOThread]
    Called [6658][Chrome_IOThread]
    Called [6658][Chrome_IOThread]
D/AudioTrackShared: front(0x12800), mIsOut 1, avail 2048, mFrameCount 4096, filled 2048
V/AudioTrack: obtainBuffer(2048) returned 2048 = 2048 + 0 err 0
D/AudioTrackShared: front(0x12800), mIsOut 1, avail 0, mFrameCount 4096, filled 4096
    front(0x12800), mIsOut 1, avail 0, mFrameCount 4096, filled 4096
    front(0x12800), mIsOut 1, obtainBuffer() FUTEX_WAIT
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xe12fff3c in tid 27394 (Chrome_InProcRe)
D/AudioTrackShared: front(0x13000), mIsOut 1, avail 2048, mFrameCount 4096, filled 2048
V/AudioTrack: obtainBuffer(2048) returned 2048 = 2048 + 0 err 0
D/AudioTrackShared: front(0x13000), mIsOut 1, avail 0, mFrameCount 4096, filled 4096
    front(0x13000), mIsOut 1, avail 0, mFrameCount 4096, filled 4096
    front(0x13000), mIsOut 1, obtainBuffer() FUTEX_WAIT
I/Choreographer: Skipped 86 frames!  The application may be doing too much work on its main thread.

Please do not give up work. I believe in you that you can revive this project =) Sorry for my bad English.

**Comment by SithisDev** [comment]
The first error occurs during incorrect work with threads. Which close with application crash.

The second error occurs when using WebAssembly + Webgl. I decided to check and download the old Google Chrome v.58 browser. The same mistake. This is a problem of the chrome itself of this version, it cannot be fixed here.

It would be nice if you build Crosswalk based on Chromium with a higher version.

**Comment by ks32** [comment]
You will need to use an older crosswalk for anything less than Android 6.0.
Make two flavours for your app. One will be a legacy which should use the
old crosswalk.


Quran Majeed for iOS and Android
<https://quranmajeed.page.link/RGhFYwtYUVwBbTnB9>

Pakistan Data Management Services
p: +92 21 3455 9003
w: www.pakdata.com
<https://facebook.com/pakdata>   <https://twitter.com/hashtag/Pakdata>
<https://www.instagram.com/pakdataapps/>
