### ISSUE TITLE
Android 29

### ISSUE THREAD

**Issue by itsmecom** [ks32/CrosswalkNative#21]
Hello, 
Google Play Store had stopped accepting app with targetSdkVersion 28.

We should atleast use sdk version 29.
But your code is crashing with targetSdkVersion 29

`E/chromium: [ERROR:compositor_impl_android.cc(585)] Failed to init OutputSurface for compositor.`

Please give me a fix

**Comment by ks32** [comment]
fixed with chromium 77

**Comment by itsmecom** [comment]
can i use it with apache cordova
