### ISSUE TITLE
Adding x86_64 xwalk_core_library-77

### ISSUE THREAD

**Issue by SithisDev** [ks32/CrosswalkNative#22]
Can x86_64 architecture be added for xwalk_core_library-77 ?

**Comment by ks32** [comment]
yes it's possible. Just need to compile.
Quran Majeed for iOS and Android
<https://quranmajeed.page.link/RGhFYwtYUVwBbTnB9>

Pakistan Data Management Services
p: +92 21 3455 9003
w: www.pakdata.com
<https://facebook.com/pakdata>   <https://twitter.com/hashtag/Pakdata>
<https://www.instagram.com/pakdataapps/>
