### ISSUE TITLE
Error initializing 

### ISSUE THREAD

**Issue by tstr007** [ks32/CrosswalkNative#24]
Thanks for this library. every thing is ok on x86 but with armeabi-v7a
this error appears 
here is a screenshot for the error log....
http://i5.imgh.top/20jku2699.png
if you can do anything about it.
thanks for updating and bringing xwalk lib back alive.

**Comment by SithisDev** [comment]
This error occurs if you run the application on a device with a different architecture from the application architecture.

**Comment by tstr007** [comment]
> This error occurs if you run the application on a device with a different architecture from the application architecture.

Yes. Thanks for your response!
