### ISSUE TITLE
Remote debugging doesnt work in xwalk_core_library-77

### ISSUE THREAD

**Issue by mikrohard** [ks32/CrosswalkNative#26]
I enable remote debugging by using:
`XWalkPreferences.setValue(XWalkPreferences.REMOTE_DEBUGGING, true);`

I can see the current session in "chrome://inspect"... but clicking the Inspect button opens only an error page "HTTP/1.1 404 Not Found". Is this a known issue? Is there any workaround?

**Comment by ks32** [comment]
chrome is not able to debug. You may try chromium or edge browser.

**Comment by mikrohard** [comment]
Thanks for the quick response. I did try Chromium before... with no success. But Edge works fine.

**Comment by SinLT** [comment]
![image](https://user-images.githubusercontent.com/20736404/96950224-6accb400-151c-11eb-8db7-bbe8aafaef64.png)

**Comment by mikrohard** [comment]
Thanks... this works too. But it requires an older version of Chromium.
