### ISSUE TITLE
IndexedDB not working

### ISSUE THREAD

**Issue by SithisDev** [ks32/CrosswalkNative#29]
What can be done to make IndexedDB work properly? IndexedDB data is not saved ...
@ks32 can you please help?

**Comment by SithisDev** [comment]
I am testing IndexedDB at http://webinista.github.io/IDBTaskList/. It works in Crosswalk 23, but does not save data in CrosswalkNative (Chromium77).

**Comment by Yamilemon** [comment]
How do you make IndexedDB work? I have the same problem.
