### ISSUE TITLE
Build error > Failed to transform xwalk_main_fat-77.2.aar

### ISSUE THREAD

**Issue by maxiannunziata** [ks32/CrosswalkNative#41]
`
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform xwalk_main_fat-77.2.aar (com.pakdata.xwalk:xwalk_main_fat:77.2) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=integration}.
      > Execution failed for AarResourcesCompilerTransform: /Users/anz/Downloads/webview-master/caches/transforms-3/01e911ac7f93d00990680bd5eab1b529/transformed/jetified-xwalk_main_fat-77.2.
         > /Users/anz/Downloads/webview-master/caches/transforms-3/01e911ac7f93d00990680bd5eab1b529/transformed/jetified-xwalk_main_fat-77.2/AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform xwalk_main_fat-77.2.aar (com.pakdata.xwalk:xwalk_main_fat:77.2) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.status=integration, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: /Users/anz/Downloads/webview-master/caches/transforms-3/bf523f5ca791271cc1d5deb9f18caee2/transformed/jetified-xwalk_main_fat-77.2.aar.
         > /Users/anz/Downloads/webview-master/caches/transforms-3/bf523f5ca791271cc1d5deb9f18caee2/transformed/jetified-xwalk_main_fat-77.2.aar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org`

**Comment by josephmangmang** [comment]
related to https://github.com/ks32/CrosswalkNative/issues/39

**Comment by maxiannunziata** [comment]
the file: https://drive.google.com/file/d/1yD5AZPBPochWbXFOTaB0YGxi8-auCHg9/view?usp=sharing
