### ISSUE TITLE
Request - Can you upload the source project for xwalk_main_fat-77.3.aar generation?

### ISSUE THREAD

**Issue by maxiannunziata** [ks32/CrosswalkNative#47]
Hi,

For my project, I need to put XWalkView's BackgroundColor transparent. Because I need to put two android views:

- At the top the webview with a color.TRANSPARENT background
- In the back a video player view

When the webview background is configured to be transparent, y can add HTML overlays to any video.

An workaround for solve this, use the xWalk API to control whether the XWalkView's surface is placed on top of its window using the setZOrderOnTop() function added in this commit https://github.com/crosswalk-project/crosswalk/commit/2c1d050d5915931c9714726ac497257cf072d9c9

The setZOrderOnTop() actually is not implemented.

Can you upload the source project for xwalk_main_fat-77.3.aar generation or add setZOrderOnTop() function to the ks32.crosswalk_native package ?

T

**Comment by ks32** [comment]
it is already available.
https://github.com/ks32/crosswalk/tree/ks_chromium_77
