### ISSUE TITLE
google-service required

### ISSUE THREAD

**Issue by HYRobin** [ks32/CrosswalkNative#7]
Hi Ks32 when I gn args out/Dewfault , I got erros 
IOError: [Errno 2] No such file or directory: '../../third_party/android_tools/sdk/extras/google/m2repository/com/google/android/gms/play-services-basement/10.2.0/play-services-basement-10.2.0.aar'

See //third_party/android_tools/BUILD.gn:191:1: whence it was called.
android_aar_prebuilt("google_play_services_basement_java") {
^-----------------------------------------------------------
See //skia/BUILD.gn:391:7: which caused the file to be included.
      "//third_party/android_tools:cpu_features",
      ^-----------------------------------------
it seems need to get google_play_services, how can i di  this  thanks you!

**Comment by ks32** [comment]
you may need to run following to download dependencies:
./install-build-deps.sh
./install-build-deps-android.sh


Quran Majeed for iOS and Android
<https://quranmajeed.page.link/RGhFYwtYUVwBbTnB9>

Pakistan Data Management Services
p: +92 21 3455 9003
w: www.pakdata.com
<https://facebook.com/pakdata>   <https://twitter.com/hashtag/Pakdata>
<https://www.instagram.com/pakdataapps/>
